### ISSUE TITLE
Blog post date

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/BBElements#11]
We need some kind of tag for nicely styling dates on a blog post below (or next to) the author.

![screenshot from 2017-01-04 16-14-44](https://cloud.githubusercontent.com/assets/3193533/21661290/feb4c47a-d298-11e6-9b8a-1679f6547953.png)

**Comment by nbriz** [comment]
rather than a date object i'm gonna make a sort of general purpose <bb-div> which plays nice with <bb-container> ( meaning behaves responsively ) && then leave it up to the user how else to style it, so in ur case probably something like this:

```html
<bb-div class="date">12/25/2016</bb-div>
```
css
```css
.date { margin-top:-54px }
```
