### ISSUE TITLE
Notes in same paragraph overlap

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/BBElements#4]
Footnotes 1 & 2 are present in the same `<bb-p>` tag which causes a stacking behavior.

![screenshot from 2016-12-23 12-34-09](https://cloud.githubusercontent.com/assets/3193533/21460310/65d23c0a-c90c-11e6-87bc-8ec7bab07a32.png)

**Comment by nbriz** [comment]
...ug, gonna have to re-arrange how the marginal notes get created, in order for it to play nice at evrey break point

**Comment by nbriz** [comment]
fixed https://github.com/brangerbriz/BBElements/commit/e7546d09b54c1aba9f51de640cb43efd4d8baa84
