### ISSUE TITLE
Overlapping bb-cell contents in bb-row

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/BBElements#8]
Occurs when collapsed to mobile view

![screenshot from 2017-01-04 15-54-20](https://cloud.githubusercontent.com/assets/3193533/21660769/7cb2a00c-d296-11e6-9ca6-88946c3b06a9.png)

**Comment by nbriz** [comment]
this might need to be handled differently in different situations ( depending on how many columns a particular row has ), in the draft for the BB site i addressed it this way:
```javascript

function alignCells(){
	var rows = document.querySelectorAll('bb-row');
	for (var i = 0; i < rows.length; i++) {
		var first = rows[i].children[0];
		var second = rows[i].children[1];
		if(innerWidth<1023){
			first.setAttribute('scale',1);
			second.setAttribute('scale',1);
		} else {
			first.setAttribute('scale',1);
			second.setAttribute('scale',2);
		}
	}
}
```
